name: Pipeline
on:
  workflow_dispatch:
  
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: Run a one-line script
        run: echo Hello, world!
        
    deploy-dev:
      runs-on: ubuntu-latest
      environment:
        name: dev
        url: 'https://www.b3.com.br/pt_br/'
      needs: build
      steps:
      - name: Run a one-line script
        run: echo Deploy dev
          
    deploy-hmg:
      runs-on: ubuntu-latest
      environment:
        name: hmg
        url: 'https://www.b3.com.br/pt_br/'
      needs: deploy-dev
      steps:
      - name: Run a one-line script
        run: echo Deploy hmg
          
    deploy-prd:
      runs-on: ubuntu-latest
      environment:
        name: prd
        url: 'https://www.b3.com.br/pt_br/'
      needs: deploy-hmg
      steps:
      - name: Run a one-line script
        run: echo Deploy prd
